In [307]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [308]:
from rsvm2 import RCH
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, TapTool,HoverTool
from bokeh.models.callbacks import CustomJS
from bokeh.io import output_notebook,show
import numpy as np
output_notebook()

Loading BokehJS ...

In [423]:
pts = np.random.uniform(-.5,.5,size=(100,2))

In [436]:
L = RCH(pts,.02)
Lverts = np.stack([x[1] for x in L])
Lverts.shape[0]

155

In [437]:
f=figure(aspect_ratio=1.0)
data=ColumnDataSource({'x':Lverts[:-1,0],'y':Lverts[:-1,1]})
data2=ColumnDataSource({'x':Lverts[:,0],'y':Lverts[:,1]})
points = ColumnDataSource({'x':pts[:,0],'y':pts[:,1],'color':['blue' for i in range(pts.shape[0])],'size':[4 for i in range(pts.shape[0])]})
callback=CustomJS(args=dict(data=data,info=L,pts=points),code="""
    var selected = data.selected.indices[0];
    var support = info[selected][2]
    var special = info[selected][2][info[selected][2].length-1]
    for(let i=0; i<pts.data['color'].length;i++){
        pts.data['color'][i]=support.includes(i)?'green':'blue'
        pts.data['size'][i]=support.includes(i)?10:4
    }
    pts.data['color'][special]='#33ee00'
    pts.change.emit()
    """)
f.scatter(x='x',y='y',color='color',source=points,size='size')
f.line(x='x',y='y',color='red',source=data2)
vertices = f.circle(x='x',y='y',selection_color='red',color='red',nonselection_fill_alpha=.5,size=10,source=data)
f.add_tools(TapTool(callback=callback,renderers=[vertices]))
show(f)

In [350]:
data.data['x'].shape[0]

13

In [257]:
pts[7]

array([0.33687028, 2.55134089])

In [233]:
from scipy.special import binom

In [234]:
binom(20,10)

184756.0

In [259]:
L[1]

Vertex(support=array([[0.33687028, 2.55134089],
       [1.58726138, 1.92047281]]), vertex=array([0.96206583, 2.23590685]), indices=array([0, 3]))

In [260]:
pts[0]

array([1.8476998 , 0.50140033])

In [261]:
pts[3]

array([-1.82038829, -0.38940463])