In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from rsvm2 import RCH
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, TapTool,HoverTool
from bokeh.models.callbacks import CustomJS
from bokeh.io import output_notebook,show
import numpy as np
output_notebook()

Loading BokehJS ...

In [3]:
pts = np.random.uniform(-.5,.5,size=(50,2))

In [4]:
L = RCH(pts,.3)
Lverts = np.stack([x[0] for x in L])
Lverts.shape[0]

61

In [5]:
f=figure(aspect_ratio=1.0)
data=ColumnDataSource({'x':Lverts[:-1,0],'y':Lverts[:-1,1]})
data2=ColumnDataSource({'x':Lverts[:,0],'y':Lverts[:,1]})
points = ColumnDataSource({'x':pts[:,0],'y':pts[:,1],'color':['blue' for i in range(pts.shape[0])],'size':[4 for i in range(pts.shape[0])]})
callback=CustomJS(args=dict(data=data,info=L,pts=points),code="""
    var selected = data.selected.indices[0];
    var support = info[selected][1]
    var special = info[selected][1][info[selected][1].length-1]
    for(let i=0; i<pts.data['color'].length;i++){
        pts.data['color'][i]=support.includes(i)?'green':'blue'
        pts.data['size'][i]=support.includes(i)?10:4
    }
    pts.data['color'][special]='#33ee00'
    pts.change.emit()
    """)
f.scatter(x='x',y='y',color='color',source=points,size='size')
f.line(x='x',y='y',color='red',source=data2)
vertices = f.circle(x='x',y='y',selection_color='red',color='red',nonselection_fill_alpha=.5,size=10,source=data)
f.add_tools(TapTool(callback=callback,renderers=[vertices]))
show(f)

In [6]:
data.data['x'].shape[0]

60

In [7]:
pts[7]

array([0.29071958, 0.38699287])

In [8]:
from scipy.special import binom

In [9]:
binom(20,10)

184756.0

In [10]:
L[1]

Vertex(vertex=array([-0.08082811,  0.42549456]), indices=array([17, 40, 27,  7]))

In [11]:
pts[0]

array([ 0.0263521 , -0.11357338])

In [12]:
pts[3]

array([0.41302107, 0.09682571])